### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by igarridomorillas** [anaguerraabaroa/AdalabLandingPage#1]
Muy buen trabajo @anaguerraabaroa!!!

Aquí tienes unos consejos para mejorar tu ejercicio:

Puntuación: 285 / 347
- [x] HTML > HEADER: La etiqueta `img` debe tener el atributo `title`.
- [x] HTML > HEADER: Los enlaces tienen que tener el atributo `title`.
- [x] CSS > PADDING: El padding de los enlaces no debería ser 0. Auméntalo para aumentar el área clickable, pero manteniendo los requisitos del diseño.
- [x] CSS > FIXED: La cabecera debe estar fija en la parte superior de la página y con `top: 0`.
- [x] CSS > FIXED: La cabecera debe medir todo el ancho de la página (cuando esté fija).

Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.

Y recuerda algo muy importante (sólo como recordatorio, porque los mensajes de los commit y los nombres de las clases están perfectos):

- Escribe tu código en inglés.
- Escribe todos los ficheros y carpetas en inglés.
- Los commits también tienen que ser en inglés empezando por un verbo en infinitivo.

Ánimo y si tienes cualquier duda avísame!!!

> Este issue ha sido creado automáticamente por ello puede tener algún error, si hay algo que no te encaja dímelo cuanto antes por favor.

> Para corregir el ejercicio buscamos determinadas palabras en el código para identificar las secciones. Por ejemplo buscamos **Anonymous** para buscar el hero. Si has escrito mal alguna palabra en el código es posible que te aparezcan aquí falsos errores.

Por favor no cierres este issue, ya lo haremos nosotros.

**Comment by anaguerraabaroa** [comment]
@igarridomorillas perdona porque no te había avisado, el ejercicio está corregido y subido a la rama master. 
En la rama migration subí un ejercicio de clase que utilizaba el ejercicio de la evaluación intermedia para explicar las migraciones de proyectos.

**Comment by igarridomorillas** [comment]
Está todo perfecto, Ana! Por cierto, puedes ir clickando en los check [ ] según vas completando las indicaciones
